### ISSUE TITLE
Convoy crashes in non-multi tenant mode.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#626]
I ran `convoy server` with the following config: 

```json
{
  "environment": "development",
  "multiple_tenants": false,
  "database": {
    "type": "in-memory",
    "dsn": "db.db"
  },
  "queue": {
    "type": "in-memory"
  },
  "server": {
    "http": {
      "ssl": false,
      "ssl_cert_file": "",
      "ssl_key_file": "",
      "port": 5005
    }
  },
  "group": {
    "signature": {
      "header": "X-Company-WebHook-Signature",
      "hash": "SHA256"
    },
    "strategy": {
      "type": "default",
      "default": {
        "intervalSeconds": 20,
        "retryLimit": 3
      }
    }
  },
  "smtp": {
    "provider": "sendgrid",
    "url": "smtp.sendgrid.net",
    "port": 2525,
    "username": "apikey",
    "password": "<api-key-from-sendgrid>",
    "from": "support@frain.dev"
  },
  "disable_endpoint": false,
  "auth": {
    "require_auth": true,
    "file": {
      "basic": [
        {
          "username": "default",
          "password": "default",
          "role": {
            "type": "super_user",
            "groups": ["sendcash-pay", "buycoins-api"]
          }
        },
        {
          "username": "convoy",
          "password": "convoy",
          "role": {
            "type": "admin",
            "groups": ["sendcash-pay", "buycoins-api"]
          }
        },
        {
          "username": "termii-user",
          "password": "convoy",
          "role": {
            "type": "admin",
            "groups": ["termii"]
          }
        }
      ],
      "api_key": [
        {
          "api_key": "<insert-api-key>",
          "role": {
            "type": "super_user",
            "groups": ["sendcash-pay"]
          }
        }
      ]
    }
  }
}

```
Then I did the following:
1. Created an application.
2. Created an endpoint.
3. Published an event.

The result:
```go
goroutine 1902 [running]:
github.com/frain-dev/convoy/worker/task.ProcessEventCreated.func1(0x14005b5af90)
        /home/runner/work/convoy/convoy/worker/task/process_event_creation.go:26 +0xd0
reflect.Value.call({0x1019eb020, 0x14000191260, 0x13}, {0x101346130, 0x4}, {0x14002646000, 0x1, 0x1})
        /opt/hostedtoolcache/go/1.17.8/x64/src/reflect/value.go:556 +0x5a8
reflect.Value.Call({0x1019eb020, 0x14000191260, 0x13}, {0x14002646000, 0x1, 0x1})
        /opt/hostedtoolcache/go/1.17.8/x64/src/reflect/value.go:339 +0x8c
github.com/frain-dev/taskq/v3.(*reflectFunc).HandleMessage(0x1400cd2c300, 0x14004b20a90)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/handler.go:78 +0x78
github.com/frain-dev/taskq/v3.(*Task).HandleMessage(0x1400cd2c330, 0x14004b20a90)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/task.go:112 +0x90
github.com/frain-dev/taskq/v3.(*TaskMap).HandleMessage(0x10235df40, 0x14004b20a90)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/registry.go:71 +0x84
github.com/frain-dev/taskq/v3.(*Consumer).Process(0x140002f0b40, 0x14004b20a90)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/consumer.go:537 +0x15c
github.com/frain-dev/taskq/v3.(*Consumer).worker(0x140002f0b40, {0x101bb7da8, 0x14000122000}, 0x32a)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/consumer.go:478 +0x180
github.com/frain-dev/taskq/v3.(*Consumer).addWorker.func1(0x140002f0b40, {0x101bb7da8, 0x14000122000}, 0x32a)
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/consumer.go:278 +0x6c
created by github.com/frain-dev/taskq/v3.(*Consumer).addWorker
        /home/runner/go/pkg/mod/github.com/frain-dev/taskq/v3@v3.2.11/consumer.go:276 +0x158
```

**Comment by u12206050** [comment]
I have the same issue, except I actually do have multi tenant setup. But exactly same error output.

```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xdd1dc2]
```
